## Base class for nimble function list quadrature grids.
QUAD_CACHE_BASE <- nimbleFunctionVirtual(
    run = function() {},
    methods = list(
        cacheQuadGrid = function(levels = double(), nodes = double(2), wgts = double(1), 
                                 modeI = integer(), prune = double(0, default = 0)) {
        },
        nodes = function(indx = integer(0, default = 0)) {
            returnType(double(2))
        },
        weights = function(indx = integer(0, default = 0)) {
            returnType(double(1))
        },
        modeIndex = function() {
            returnType(integer())
        },
        gridSize = function() {
            returnType(integer())
        },
        checkGrid = function(levels = double(0, default = -1), d = integer(0, default = 1), prune = double(0, default = 0)) {
            returnType(logical())
        }
    )
)

## Method for summing likelihoods on real scale with possible small values.
## Returns back on log scale.
#' @export
logSumExp = nimbleFunction(run = function(log1 = double(), log2 = double()) {
    if (log1 > log2) {
        ans <- log(1 + exp(log2 - log1)) + log1
    } else ans <- log(1 + exp(log1 - log2)) + log2
    returnType(double())
    return(ans)
}, buildDerivs = list(run = list()))

#' Caching system for building multiple quadrature grids.
#'
#' Save the quadrature grid generated by a chosen rule and return it upon request.
#' 
#'
#' @details
#' This function is intended to be used within another NIMBLE function to conveninetly cache multiple quadrature grids. 
#' It cannot be compiled without being included within a virtual nimble list "QUAD_CACHE_BASE".
#'
#' @author Paul van Dam-Bates
#'
#'
#'
#' @export
quadGridCache <- nimbleFunction(
    contains = QUAD_CACHE_BASE,
    setup = function() {
        quadGridList_internal <- quadGridListDef
        nodes_cached <- matrix(0, nrow = 1, ncol = 1)
        weights_cached <- c(0, 0)
        modeIndex_cached <- -1
        nGrid_cached <- 0L
        gridBuilt <- FALSE
        prune_ <- 0
        levels_ <- 0
        constructionRule_ <- "notset" 
        d_ <- 1
    },
    run = function() {
    },
    methods = list(
     cacheQuadGrid = function(levels = double(), nodes = double(2), wgts = double(1),
                                 modeI = integer(), prune = double(0, default = 0)) {
        nodes_cached <<- nodes
        weights_cached <<- wgts
        modeIndex_cached <<- modeI
        nGrid_cached <<- dim(nodes_cached)[1]
        gridBuilt <<- TRUE
        levels_ <<- levels
        prune_ <<- prune
        d_ <<- dim(nodes_cached)[2]
    },
    checkGrid = function(levels = double(0, default = -1), d = integer(0, default = 1), prune = double(0, default = -1)) {
        returnType(logical())
        if (!gridBuilt | (levels != levels_) | (prune_ != prune) | (d_ != d))
            return(FALSE) else return(TRUE)
    },
    nodes = function(indx = integer(0, default = 0)) {
        returnType(double(2))
        if (indx > 0) {
            if(indx > nGrid_cached) stop("Trying to access more quadrature nodes than there are.")
            return(matrix(nodes_cached[indx, ], nrow = 1))
        }
        if (indx == -1 & modeIndex_cached > 0)
            return(matrix(nodes_cached[modeIndex_cached, ], nrow = 1))
        if(indx > nGrid_cached)
          stop("Asking for more quadrature points than available.")
        return(nodes_cached)
    },
    weights = function(indx = integer(0, default = 0)) {
        returnType(double(1))
        if (indx > 0){
            if(indx > nGrid_cached) stop("Trying to access more quadrature nodes than there are.")
            return(numeric(value = weights_cached[indx], length = 1))
        }
        if (indx == -1 & modeIndex_cached > 0)
            return(numeric(value = weights_cached[modeIndex_cached], length = 1))
        if(indx > nGrid_cached)
          stop("Asking for more quadrature points than available.")
        return(weights_cached)
    },
    modeIndex = function() {
        returnType(integer())
        return(modeIndex_cached)
    },
    gridSize = function() {
        returnType(integer())
        return(nGrid_cached)
    }
  )
)


#' Configure Quadrature Grids
#'
#' Takes requested quadrature rules, builds the associated quadrature grids, and caches them. Can update 
#' all the features of the grids.
#' 
#'
#' @param d Number of dimensions.
#' @param levels Number of quadrature points to generate in each dimension (or the level of accuracy of a sparse grid).
#' @param quadRule Default quadRule to be used. Options are "AGHQ", "CCD", "USER".
#' @param control list that incudes  `quadRules` which should include all the different rules that of interest. `constructionRule` to choose
#' between a product combination of the quadrature rule in each dimension ("product"), or sparse quadrature rules ("sparse").
#' CCD_f0 multiplier for the CCD grid for how much past the radius sqrt(d) to extend the nodes. Unless an advanced user, keep at default of 1.1.
#' prune the proportion of quadrature points (when generated by the product rule) to keep based on the weights for integration over a multivariate normal.
#'
#' @details
#'   \item \code{buildGrid} method for creating the quadrature grid. Inputs are \code{method} includes ("AGHQ", "CCD", "USER") to choose the quadrature rule. 
#'   \code{nQuad} number of quadrature points (nQuad) per dimension, \code{prune} proportion of points in the product construction to use, and \code{constructionRule} 
#'   includes ("product", "sparse"). Default behaviour for all input is to use whatever values are currently being used. 
#'
#'   \item \code{setDim} Allows the user to change the dimension of the quadrature grids which will reset all grids in use.
#'
#'   \item \code{nodes}, \code{weights}, \code{gridSize}, and \code{modeIndex} give access to the user for the details of the quadrature grid in use. This is either based
#'   on the last call to \code{buildGrid}, or by choosing a different grid with \code{setMethod}. \code{nodes} and \code{weights} return all nodes and weights if no values
#'   are passed, or if an index is passed, the node and weight associated with that index. Passing -1 indicates that the mode should be returned which in this case is all zeros.
#'
#'
#' @author Paul van Dam-Bates
#'
#' @export
configureQuadGrid <- nimbleFunction(
    name = "quadGridClass",
    setup = function(d = 1, levels = 3, quadRule = "AGHQ", control = list()) {
        ## Can list all possible quad rules here and set it.
        possibleRules <- c("AGHQ", "CCD", "AGHQSPARSE", "USER", "USERSPARSE", "USERMULTI")
        
        quadRules <- extractControlElement(control, "quadRules", NULL)
        ccd_f0 <- extractControlElement(control, "CCD_f0", 1.1)

        prune_ <- extractControlElement(control, "prune", 0)
        if (prune_ > 1 | prune_ < 0)
            stop("Can only prune a proportion of quadrature points.")
        
        if (!any(quadRule == quadRules))
            quadRules <- c(quadRule, quadRules)

        if (!all(quadRules %in% possibleRules))
            stop("Error:  Only AGHQ, CCD, AGHQSPARSE, USER, USERSPARSE, or USERMULTI suplied rules are currently implemented.")

        numError <- 1e-16

        quadGridList_internal <- quadGridListDef
        quadGridCache_nfl <- nimbleFunctionList(QUAD_CACHE_BASE)
        quadRule_nfl <- nimbleFunctionList(QUAD_RULE_BASE)

        I_AGHQ <- I_CCD <- I_USER <- I_AGHQSPARSE <- I_USERSPARSE <- I_USERMULTI <- -1
        I_RULE <- which(quadRules == quadRule)[1]

        ## ***CJP please comment on this! Probably smarter way to do this...
        userRuleProvided <- exists("quadRule_USER")
        if(!userRuleProvided & any(quadRules %in% c("USER", "USERMULTI", "USERSPARSE")))
          stop("For user provided quadrature rules, a nimble function with name `quadRule_User` must be provided.")

        nRules <- length(quadRules)
        for (i in 1:nRules) {
            if (quadRules[i] == "AGHQ") {
                I_AGHQ <- i
                quadRule_nfl[[i]] <- quadRule_GH(type="GHe")
            }else if (quadRules[i] == "CCD") {
                I_CCD <- i
                quadRule_nfl[[i]] <- quadRule_CCD(f0 = ccd_f0)
            }else if (quadRules[i] == "AGHQSPARSE") {
                I_AGHQSPARSE <- i
                quadRule_nfl[[i]] <- quadRule_GH(type="GHe")
            }else if (quadRules[i] == "USER") {
                I_USER <- i
                quadRule_nfl[[i]] <- quadRule_USER()
            }else if (quadRules[i] == "USERSPARSE") {
                I_USERSPARSE <- i
                quadRule_nfl[[i]] <- quadRule_USER()
            }else if (quadRules[i] == "USERMULTI") {
                I_USERMULTI <- i
                quadRule_nfl[[i]] <- quadRule_USER()
            }else{
              stop("An unrecognized quadRule was detected.")
            }
            quadGridCache_nfl[[i]] <- quadGridCache()            
        }
        gridBuilt <- rep(FALSE, nRules)
        nGrid <- numeric(nRules)
        modeI <- -1L + integer(nRules)
        if(nRules == 1){
          gridBuilt <- c(gridBuilt, FALSE)
          nGrid <- c(nGrid, 0)
          quadRules <- c(quadRules, "NULL")
        }        
    },
    run = function() {
    },
    methods = list(
        ## NOCHNG means keep it as is, and nQuad = -1.
        buildGrid = function(method = character(0, default = "NULL"),
                             nQuad = integer(0, default = -1), 
                             prune = double(0, default = -1)) {
            if ( method != "NULL" ) setRule(method)
            if ( nQuad != -1 ) levels <<- nQuad
            if(prune != -1) prune_ <<- prune
            if ( !quadGridCache_nfl[[I_RULE]]$checkGrid(levels = levels, d = d, prune = prune_) ) {
              newGrid()
            }
            modeI[I_RULE] <<- quadGridCache_nfl[[I_RULE]]$modeIndex()
            nGrid[I_RULE] <<- quadGridCache_nfl[[I_RULE]]$gridSize()
        },
        newGrid = function(){
          ## No sparse or product rule for d=1. User can provide a multivariate grid similar to CCD as well.
          if ( any(I_RULE == c(I_CCD, I_USERMULTI)) | d == 1){
            nodes_wgts <- quadRule_nfl[[I_RULE]]$buildGrid(levels = levels, d = d)
          }else{
            if ( any(I_RULE == c(I_AGHQSPARSE, I_USERSPARSE)) ){
              nodes_wgts <- sparse_construction()
            }else{
              levels_vec <- numeric(value = levels, length = d) ## In theory we can choose a different number of nodes per dimension.
              nodes_wgts <- product_construction(levels_vec = levels_vec)
            }
          }
          if(dim(nodes_wgts)[2] != d+1)
            stop("Quadrature Grid is not the correct number of dimensions.")

          findModeIndex(nodes_wgts)
          
          if(prune_ > 0)
            nodes_wgts <- pruneGrid(nodes_wgts)
          
          nGrid[I_RULE] <<- dim(nodes_wgts)[1]
          quadGridCache_nfl[[I_RULE]]$cacheQuadGrid(levels = levels, nodes = matrix(nodes_wgts[,2:(d+1)], ncol = d, nrow = nGrid[I_RULE]),
                                                      wgts = nodes_wgts[,1], modeI = modeI[I_RULE], prune = prune_)
            
          gridBuilt[I_RULE] <<- TRUE
        },
        findModeIndex = function(nodes_wgts = double(2)){
          modei <- -1L
          if(I_RULE == I_CCD) {
            modei <- 1
          }else {
            nQ <- dim(nodes_wgts)[1]
            if(nQ %% 2 == 0 & any(I_RULE == c(I_AGHQ, I_USER, I_USERMULTI))){
              modei <- -1
            }else {
              modei <- ceiling(nQ/2)
              if (sum(abs(nodes_wgts[modei, 2:(d + 1)])) != 0) {
                for (i in 1:nQ) {
                    if (sum(abs(nodes_wgts[i, 2:(d + 1)])) == 0) modei <- i
                }
              }
            }
          }
          modeI[I_RULE] <<- as.integer(modei)
        },
        ## Prune grid and then cache it again.
        pruneGrid = function( nodes_wgts = double(2) ) {
            if ( prune_ > 1 | prune_ < 0 ) stop("Can only prune a proportion of quadrature points.")
            nQ <- dim(nodes_wgts)[1]
            if (I_RULE != I_CCD | prune_ == 0) {
                ntrim <- 0
                ## Adjust weights:
                log_weights_adj <- numeric(value = 0, length = nQ)
                for (i in 1:nQ) {
                    log_weights_adj[i] <- sum(dnorm(nodes_wgts[i,2:(d+1)], mean = 0, sd = 1, log = TRUE)) +
                        log(nodes_wgts[i,1])
                }
                ## Bubble sort as we don't have a quantile function.
                order <- 1:nQ
                for( k in 1:(nQ-1) ){
                  i <- 1
                  while( i < nQ-k+1 ){
                    if(log_weights_adj[order[i]] > log_weights_adj[order[i+1]]) {
                      tmp <- order[i+1]
                      order[i+1] <- order[i]
                      order[i] <- tmp
                    }
                  i <- i+1
                  }
                }
                ntrim <- ceiling(nQ*prune_)
                q <- log_weights_adj[order][ntrim]
                keep <- which(log_weights_adj > q + numError) ## Matching weights can be numerically different and want to trim symmetrically.
                if(dim(keep)[1] >= 3) {
                  nodes_wgts <- nodes_wgts[keep,]
                  if (modeI[I_RULE] > 0) {
                      modei <- which(keep == modeI[I_RULE] )
                      if (dim(modei)[1] > 0) modeI[I_RULE]  <<- modei[1] else modeI[I_RULE] <<- -1
                  }
                }else{
                  stop("Will not prune to less than 3 quadrature points. Choose another pruning proportion or switch to Laplace, one quadrature node.")
                }
            }
            returnType(double(2))
            return(nodes_wgts)
        },
        product_construction = function(levels_vec = double(1)) {
            nQ <- prod(levels_vec)
            nodes_wgts <- matrix(1, nrow = nQ, ncol = d + 1)

            ## Get quad grid
            nodes_mat <- matrix(0, nrow = d, ncol = max(levels_vec))
            weights_vec <- matrix(0, nrow = d, ncol = max(levels_vec))
            for (i in 1:d) {
                nodesi <- quadRule_nfl[[I_RULE]]$buildGrid(levels_vec[i], d = 1)
                nodes_mat[i, 1:levels_vec[i]] <- nodesi[, 2]
                weights_vec[i, 1:levels_vec[i]] <- nodesi[, 1]
            }

            swp <- nimNumeric(value = 0, length = d)
            swp[1] <- 1
            for (ii in 2:d) swp[ii] <- prod(levels_vec[1:(ii - 1)])

            ## Do Product Rule: Repeat x for each dimension swp times.
            for (j in 1:d) {
                indx <- 1
                for (ii in 1:nQ) {
                    nodes_wgts[ii, j + 1] <- nodes_mat[j, indx]
                    nodes_wgts[ii, 1] <- nodes_wgts[ii, 1] * weights_vec[j, indx]
                    k <- ii %% swp[j]
                    if (k == 0)
                        indx <- indx + 1
                    if (indx > levels_vec[j])
                        indx <- 1
                }
            }
            returnType(double(2))
            return(nodes_wgts)
        },
        sparse_construction = function() {
            if( any(I_RULE == c(I_AGHQSPARSE, I_USERSPARSE)) ){
              minq <- max(0, levels - d)
              maxq <- levels - 1

              noSubGrids <- sum(factorial(minq:maxq + d - 1) / (factorial(minq:maxq) * factorial(d - 1)))

              gridCombos <- matrix(0, nrow = noSubGrids, ncol = d)
              start <- 1
              for (q in minq:maxq) {
                  tmpCombos <- drop_algorithm(d, d + q)
                  nq <- dim(tmpCombos)[1]
                  gridCombos[start:(start + nq - 1), ] <- tmpCombos
                  start <- start + nq
              }

              totalPts <- 0
              for (i in 1:noSubGrids) {
                  totalPts <- totalPts + prod(gridCombos[i, ])
              }
              nodes_wgts <- matrix(0, nrow = totalPts, ncol = d + 1)
              cnt <- 1
              for (i in 1:noSubGrids) {
                  q <- sum(gridCombos[i, ]) - d
                  wgtadj <- (-1)^(maxq - q) * factorial(d - 1) / (factorial(d + q - levels) *
                      factorial(levels - q - 1))

                  nodes_prod <- product_construction(levels_vec = gridCombos[i, ])
                  nodes_wgts[cnt:(cnt + dim(nodes_prod)[1] - 1), 1] <- nodes_prod[, 1] * wgtadj
                  nodes_wgts[cnt:(cnt + dim(nodes_prod)[1] - 1), 2:(d + 1)] <- nodes_prod[, 2:(d + 1)]

                  cnt <- cnt + dim(nodes_prod)[1]
              }
            }else{
              stop("Trying to apply sparse construction to an invalid quadrature rule.")
            }
            returnType(double(2))
            return(nodes_wgts)            
        },
        ## Surely there is a better way to do this...
        setRule = function(method = character(0, default = "AGHQ")) {
            success <- FALSE
            i <- 1
            while(i <= nRules & !success){
              if(quadRules[i] == method){
                I_RULE <<- i
                success <- TRUE
              }
              i <- i+1
            }
            if( !success ) {
              stop("Quadrature Rule being requested was either not created or is invalid. Choose a valid quadrature rule.")
            }
        },
        setDim = function(ndim = integer(0, default = 1)) {
            if (ndim <= 0) stop("Can't input negative dimensions") else d <<- ndim
            ## Make sure the next grid gets built.
            for( i in 1:nRules ) gridBuilt[i] <<- FALSE
        },
        weights = function(indx = integer(0, default = 0)) {
            if (!gridBuilt[I_RULE]) buildGrid()
            if (indx == -1 & modeI[I_RULE] > 0) indx <- modeI[I_RULE] 
            returnType(double(1))
            return(quadGridCache_nfl[[I_RULE]]$weights(indx = indx))
        },
        nodes = function(indx = integer(0, default = 0)) {
            if (!gridBuilt[I_RULE]) buildGrid()
            if (indx == -1 & modeI[I_RULE]  > 0) indx <- modeI[I_RULE] 
            returnType(double(2))
            return(quadGridCache_nfl[[I_RULE]]$nodes(indx = indx))
        },
        gridSize = function() {
            if (!gridBuilt[I_RULE]) buildGrid()
            returnType(double())
            return(nGrid[I_RULE])
        },
        modeIndex = function() {
            if (!gridBuilt[I_RULE]) buildGrid()
            returnType(double())
            return(modeI[I_RULE] )
        }
    )
)  ## End of configureQuadGrid


#' Build Adaptive Gauss-Hermite Quadrature Grid
#'
#' Create quadrature grid for use in AGHQuad methods in Nimble.
#'
#' @param d Dimension of quadrature grid being requested.
#'
#' @param nQuad Number of quadrature nodes requested on build.
#'
#' @name buildAGHQGrid
#' 
#' @details
#'
#' This function is used by used by \code{buildOneAGHQuad1D}
#' and \code{buildOneAGHQuad} create the quadrature grid using
#' adaptive Gauss-Hermite quadrature. Handles single or multiple dimension 
#' grids and computes both grid locations and weights. Additionally, acts
#' as a cache system to do transformations, and return marginalized log density.
#'
#' Any of the input node vectors, when provided, will be processed using
#'   \code{nodes <- model$expandNodeNames(nodes)}, where \code{nodes} may be
#'   \code{paramNodes}, \code{randomEffectsNodes}, and so on. This step allows
#'   any of the inputs to include node-name-like syntax that might contain
#'   multiple nodes. For example, \code{paramNodes = 'beta[1:10]'} can be
#'   provided if there are actually 10 scalar parameters, 'beta[1]' through
#'   'beta[10]'. The actual node names in the model will be determined by the
#'   \code{exapndNodeNames} step.
#'
#' Available methods include
#' 
#' \itemize{
#'
#'   \item \code{buildAGHQ}. Builds a adaptive Gauss-Hermite quadrature grid in d dimensions.
#'   Calls \code{buildAGHQOne} to build the one dimensional grid and then expands in each dimension.
#'   Some numerical issues occur in Eigen decomposition making the grid weights only accurate up to 
#'   35 quadrature nodes.
#'
#'   \item Options to get internally cached values are \code{getGridSize},
#'   \code{getModeIndex} for when there are an odd number of quadrature nodes,
#'   \code{getLogDensity} for the cached values, \code{getAllNodes} for the 
#'   quadrature grids, \code{getNodes} for getting a single indexed nodes,
#'   \code{getAllNodesTransformed} for nodes transformed to the parameter scale,
#'   \code{getNodesTransformed} for a single transformed node, \code{getAllWeights} 
#'   to get all quadrature weights, \code{getWeights} single indexed weight.
#'
#'   \item \code{transformGrid(cholNegHess, inner_mode, method)} transforms 
#'   the grid using either cholesky trasnformations,
#'   as default, or spectral that makes use of the Eigen decomposition. For a single
#'   dimension \code{transformGrid1D} is used.
#'
#'   \item As the log density is evaluated externally, it is saved via \code{saveLogDens},
#'   which then is summed via \code{quadSum}.
#'
#'   \item \code{buildGrid} builds the grid the initial time and is only run once in code. After,
#'   the user must choose to \code{setGridSize} to update the grid size.
#'
#'
#'   \item \code{check}. If TRUE (default), a warning is issued if
#'         \code{paramNodes}, \code{randomEffectsNodes} and/or \code{calcNodes}
#'         are provided but seek to have missing elements or unnecessary
#'         elements based on some default inspection of the model. If
#'         unnecessary warnings are emitted, simply set \code{check=FALSE}.
#'
#'   \item \code{innerOptimControl}. A list of control parameters for the inner 
#'         optimization of Laplace approximation using \code{optim}. See 
#'         'Details' of \code{\link{optim}} for further information.
#'
#'   \item \code{innerOptimMethod}. Optimization method to be used in 
#'         \code{optim} for the inner optimization. See 'Details' of 
#'         \code{\link{optim}}. Currently \code{optim} in NIMBLE supports: 
#'         '\code{Nelder-Mead}', '\code{BFGS}', '\code{CG}', and 
#'         '\code{L-BFGS-B}'. By default, method '\code{CG}' is used when 
#'         marginalizing over a single (scalar) random effect, and '\code{BFGS}' 
#'         is used for multiple random effects being jointly marginalized over.
#'
#'   \item \code{innerOptimStart}. Choice of starting values for the inner 
#'         optimization. This could be \code{'last'}, \code{'last.best'}, or a 
#'         vector of user provided values. \code{'last'} means the most recent 
#'         random effects values left in the model will be used. When finding 
#'         the MLE, the most recent values will be the result of the most recent 
#'         inner optimization for Laplace. \code{'last.best'} means the random 
#'         effects values corresponding to the largest Laplace likelihood (from 
#'         any call to the \code{calcLaplace} or \code{calcLogLik} method, 
#'         including during an MLE search) will be used (even if it was not the 
#'         most recent Laplace likelihood). By default, the initial random 
#'         effects values will be used for inner optimization.
#'
#'   \item \code{outOptimControl}. A list of control parameters for maximizing
#'         the Laplace log-likelihood using \code{optim}. See 'Details' of
#'         \code{\link{optim}} for further information.
#' }
#'
#' @references
#'
#' Golub, G. H. and Welsch, J. H. (1969). Calculation of Gauss Quadrature Rules. 
#' Mathematics of Computation 23 (106): 221-230.
#'
#' Liu, Q. and Pierce, D. A. (1994). A Note on Gauss-Hermite Quadrature. Biometrika, 81(3) 624-629.
#'
#' Jackel, P. (2005). A note on multivariate Gauss-Hermite quadrature. London: ABN-Amro. Re.
#'
NULL


## Create a caching random effects system for simulating the posterior random
## effect distribution according to Stringer: This requires the inner mode, the
## inner cholesky, the

INNER_CACHE_BASE <- nimbleFunctionVirtual(
    run = function() {
    },
    methods = list(
        buildCache = function(nGridUpdate = integer(), nLatentNodes = integer()) {},
        cache_weights = function(weight = double(), indx = integer()) {},
        cache_inner_mode = function(mode = double(1), indx = integer()) {},
        cache_inner_negHessChol = function(negHessChol = double(2), indx = integer()) {},
        weights = function() {
            returnType(double(1))
        },
        simulate = function(n = integer()) {
            returnType(double(2))
        }
    )
)

## Things I need to add for approx posterior save inner mode, save inner
## cholesky etc. for doing simulation of random-effects save outer mode and
## negHessian.  Need wgt*density and inner mode and inner cholesky for each
## point:
inner_cache_methods = nimbleFunction(
    contains = INNER_CACHE_BASE,
    setup = function(nre = 0, nGrid = 0, condIndptSets = NULL, nCondIndptSets = 1) {
        innerMode <- matrix(0, nrow = 1, ncol = 1)
        innerNegHessChol <- array(0, c(1, 1, 1))
        wgtsDens <- c(1, -1)
        cacheBuilt <- FALSE
        if (is.null(condIndptSets)) {
            condIndptSets <- nre  ## Assuming all one set.
            nCondIndptSets <- 1  ## If NULL then this is not relevant.
        }
        if (length(condIndptSets) == 1) {
            condIndptSets <- c(condIndptSets, -1)  ##  Make sure it's a vector.
        }
    },
    run = function() {
    },
    methods = list(
        buildCache = function(nGridUpdate = integer(0, default = -1), nLatentNodes = integer()) {
            nre <<- nLatentNodes
            ## If the cond indpt sets don't match up, don't use.
            if (nre != sum(condIndptSets[1:nCondIndptSets])) {
                print("  Warning: Not able to simulate latent effects from conditionally independent sets.")
                condIndptSets <<- numeric(value = nre, length = 1)
                nCondIndptSets <<- 1
            }

            if (nGridUpdate > 0 & nGridUpdate != nGrid) {
                nGrid <<- nGridUpdate
                cacheBuilt <<- FALSE
            }
            if (!cacheBuilt) {
                nGrid <<- nGridUpdate
                wgtsDens <<- numeric(value = 0, length = nGrid)
                innerMode <<- matrix(0, nrow = nGrid, ncol = nre)
                innerNegHessChol <<- array(0, c(nGrid, nre, nre))
                cacheBuilt <<- TRUE
            }
        },
        ## Note to self, this wgt will be density*wgt, strictly for simulating.
        cache_weights = function(weight = double(), indx = integer()) {
            wgtsDens[indx] <<- weight
        },
        cache_inner_mode = function(mode = double(1), indx = integer()) {
            innerMode[indx, ] <<- mode
        },
        ## Note potentially storing a lot of zeros here. Could break it into a list of cond indpt sets.
        cache_inner_negHessChol = function(negHessChol = double(2), indx = integer()) {
            innerNegHessChol[indx, , ] <<- negHessChol
        },
        weights = function() {
            returnType(double(1))
            return(wgtsDens)
        },
        ## Adding first column to be index for theta.
        simulate = function(n = integer()) {
            val <- matrix(0, nrow = n, ncol = nre + 1)
            simwgt <- wgtsDens/sum(wgtsDens)  ## Did log sum exp when doing input.

            ## Simulate theta points first.  Seems efficient to separate to not
            ## initiate too many index vectors for cond indpt sets.
            for (i in 1:n) {
                k <- rcat(1, prob = simwgt)
                val[i, 1] <- k
                jStart <- 1
                for (j in 1:nCondIndptSets) {
                    val[i, (jStart + 1):(jStart + condIndptSets[j])] <-
                        rmnorm_chol(n = 1, mean = innerMode[k, jStart:(jStart + condIndptSets[j] - 1)],
                                    cholesky = innerNegHessChol[k, jStart:(jStart + condIndptSets[j] - 1),
                                                                jStart:(jStart + condIndptSets[j] - 1)],
                                    prec_param = TRUE)
                    jStart <- jStart + condIndptSets[j]
                }
            }
            returnType(double(2))
            return(val)
        }
    )
)
